rte-actualite:
  enabled: false
  url: https://www.rte-france.com/actualites
  img: https://upload.wikimedia.org/wikipedia/commons/thumb/1/1f/RTE_logo.svg/180px-RTE_logo.svg.png
  name: RTE Actualité
  parsers: rte_actualites
  debug: Difficile à scraper car les articles arrivent plus tard dans le cycle de vie
rte-wiki:
  enabled: false
  url: https://www.rte-france.com/wiki-energie/articles
  name: RTE Wiki Energie
  img: https://upload.wikimedia.org/wikipedia/commons/thumb/1/1f/RTE_logo.svg/180px-RTE_logo.svg.png
  debug: Difficile à scraper car les articles arrivent plus tard dans le cycle de vie
iea:
  enabled: true
  url: https://www.iea.org/news
  name: IEA
  parsers: iea_news
  img: https://upload.wikimedia.org/wikipedia/commons/thumb/f/fb/International_Energy_Agency_%28IEA%29_logo.svg/330px-International_Energy_Agency_%28IEA%29_logo.svg.png
enedis:
  enabled: false
  name: Enedis
  url: https://www.enedis.fr/presse
  img: https://www.enedis.fr/themes/custom/enedis_theme/favicon.ico
sdes:
  enabled: true
  name: sdes
  url: https://www.statistiques.developpement-durable.gouv.fr/actualites
  img: https://www.statistiques.developpement-durable.gouv.fr/themes/custom/sdes/images/logo/logo_header_rvb.png
  parsers: sdes
enedis-odte:
  enabled: true
  name: Observatoire Français de la Transition Ecologique - Enedis
  parsers: enedis_odte
  url: https://observatoire.enedis.fr/tous-les-articles
  img: https://www.enedis.fr/themes/custom/enedis_theme/favicon.ico
cre:
  enabled: true
  name: Commission de Régulation de l'Energie
  url: https://www.cre.fr/actualites/toute-lactualite.html
  parsers: cre_actualites
  img: https://www.cre.fr/_assets/eee83a27e1e6e241ed7098a5f815474c/Frontend/assets/static/logo-cre.svg
energie-mediateur:
  enabled: false
  name: Médiateur National de l'Energie
  url: https://www.energie-mediateur.fr/le-mediateur/actualites/revue-de-presse/
  debug: todo
engie:
  enabled: false
  url: https://newsroom.engie.com/news/
  debug: todo
france-renouvelables:
  enabled: false
  url: https://www.france-renouvelables.fr/actualites/
  debug: todo
agence-ore:
  enabled: false
  url: https://www.agenceore.fr/publications-actualites
  debug: todo
